spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yyy2015/HelloSpringCloud
          search-paths: properties
          
      label: master

server:
  port: 8888

